# Generated by Django 5.2.14 on 2026-05-22 06:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("telemetry", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="telemetryenvelope",
            name="source",
            field=models.CharField(
                choices=[
                    ("tenant_vm", "Tenant VM"),
                    ("audit_vm", "Audit VM"),
                    ("edge_gateway", "Edge gateway"),
                    ("miner", "Miner"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="telemetrysource",
            name="source",
            field=models.CharField(
                choices=[
                    ("tenant_vm", "Tenant VM"),
                    ("audit_vm", "Audit VM"),
                    ("edge_gateway", "Edge gateway"),
                    ("miner", "Miner"),
                ],
                max_length=32,
            ),
        ),
    ]
