# Generated by Django 5.2.14 on 2026-05-22 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0002_alter_telemetryenvelope_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telemetryenvelope',
            name='kind',
            field=models.CharField(choices=[('edge_telemetry', 'Edge telemetry envelope'), ('served_receipt', 'Tenant served-delivery receipt'), ('heartbeat', 'Miner heartbeat')], max_length=32),
        ),
    ]
