# Generated by Django 5.2.15 on 2026-07-16 10:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0003_alter_telemetryenvelope_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telemetryenvelope',
            name='source',
            field=models.CharField(choices=[('tenant_vm', 'Tenant VM'), ('audit_vm', 'Audit VM'), ('edge_gateway', 'Edge gateway'), ('miner', 'Miner'), ('host_attestor', 'Host attestor')], max_length=32),
        ),
        migrations.AlterField(
            model_name='telemetrysource',
            name='source',
            field=models.CharField(choices=[('tenant_vm', 'Tenant VM'), ('audit_vm', 'Audit VM'), ('edge_gateway', 'Edge gateway'), ('miner', 'Miner'), ('host_attestor', 'Host attestor')], max_length=32),
        ),
        migrations.CreateModel(
            name='HostAttestor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chip_id', models.CharField(max_length=128, unique=True)),
                ('node_id', models.CharField(db_index=True, max_length=256)),
                ('signer_pubkey', models.BinaryField(max_length=32)),
                ('measurement', models.CharField(max_length=96)),
                ('tcb', models.BigIntegerField(default=0)),
                ('cert_nonce', models.CharField(blank=True, default='', max_length=64)),
                ('cert_expiry_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('attested', 'Attested'), ('expired', 'Expired')], default='pending', max_length=16)),
                ('last_seq', models.BigIntegerField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('boot_id', models.CharField(blank=True, default='', max_length=256)),
                ('enrolled_at', models.DateTimeField(blank=True, null=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['node_id', 'chip_id'],
                'indexes': [models.Index(fields=['status'], name='telemetry_h_status_215afd_idx'), models.Index(fields=['node_id'], name='telemetry_h_node_id_429662_idx')],
            },
        ),
        migrations.CreateModel(
            name='HostAttestorRelease',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('measurement', models.CharField(max_length=96, unique=True)),
                ('version', models.CharField(blank=True, default='', max_length=64)),
                ('cosign_issuer', models.CharField(blank=True, default='', max_length=256)),
                ('cosign_identity', models.CharField(blank=True, default='', max_length=256)),
                ('cosign_rekor_log_index', models.BigIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active'], name='telemetry_h_is_acti_ecfe25_idx')],
            },
        ),
    ]
