# Generated by Django 5.2.16 on 2026-07-16 12:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0004_alter_telemetryenvelope_source_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostAttestorNonce',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nonce', models.BinaryField(max_length=32, unique=True)),
                ('node_id', models.CharField(db_index=True, max_length=256)),
                ('signer_pubkey', models.BinaryField(max_length=32)),
                ('expires_at', models.DateTimeField()),
                ('spent_at', models.DateTimeField(blank=True, null=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-issued_at'],
                'indexes': [models.Index(fields=['expires_at'], name='telemetry_h_expires_d87223_idx'), models.Index(fields=['node_id'], name='telemetry_h_node_id_099740_idx')],
            },
        ),
    ]
