# Generated by Django 5.2.17 on 2026-08-10 06:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0005_hostattestornonce'),
    ]

    operations = [
        migrations.CreateModel(
            name='VmLiveAttestation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vm_id', models.CharField(db_index=True, max_length=128)),
                ('node_id_hex', models.CharField(max_length=64)),
                ('attestation_seq', models.BigIntegerField()),
                ('epoch', models.BigIntegerField()),
                ('observed_at_unix', models.BigIntegerField()),
                ('verified_at_unix', models.BigIntegerField()),
                ('expiry_unix', models.BigIntegerField()),
                ('measurement', models.CharField(max_length=96)),
                ('snp_report_digest', models.CharField(max_length=64)),
                ('body_digest', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['vm_id', 'verified_at_unix'],
                'indexes': [models.Index(fields=['vm_id', 'verified_at_unix'], name='telemetry_v_vm_id_195650_idx')],
                'constraints': [models.UniqueConstraint(fields=('vm_id', 'attestation_seq'), name='telemetry_vm_live_attestation_unique_vm_seq')],
            },
        ),
    ]
