# Generated by Django 5.2.15 on 2026-09-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0008_hostattestorrelease_generation'),
    ]

    operations = [
        migrations.AddField(
            model_name='vmliveattestation',
            name='binding_source',
            field=models.CharField(blank=True, db_default='', default='', max_length=16),
        ),
        migrations.AddField(
            model_name='vmliveattestation',
            name='chip_id',
            field=models.CharField(blank=True, db_default='', default='', max_length=128),
        ),
        migrations.AddField(
            model_name='vmliveattestation',
            name='report_id',
            field=models.CharField(blank=True, db_default='', default='', max_length=64),
        ),
    ]
