# Generated by Django 5.2.15 on 2026-10-03 21:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0009_live_attestation_guest_binding'),
    ]

    operations = [
        migrations.AddField(
            model_name='vmliveattestation',
            name='mem_firmware_kib',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='vmliveattestation',
            name='mem_total_kib',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='vmliveattestation',
            name='mem_unaccepted_kib',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='vmliveattestation',
            name='resource_verdict',
            field=models.CharField(blank=True, db_default='', default='', max_length=16),
        ),
        migrations.AddField(
            model_name='vmliveattestation',
            name='vcpus_online',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.CreateModel(
            name='GuestResourceShortfall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vm_id', models.CharField(db_index=True, max_length=128)),
                ('node_id_hex', models.CharField(db_index=True, max_length=64)),
                ('flavor', models.CharField(max_length=32)),
                ('want_vcpus', models.PositiveIntegerField()),
                ('want_memory_mb', models.PositiveIntegerField()),
                ('vcpus_online', models.PositiveIntegerField(blank=True, null=True)),
                ('mem_firmware_kib', models.BigIntegerField(blank=True, null=True)),
                ('mem_total_kib', models.BigIntegerField(blank=True, null=True)),
                ('mem_unaccepted_kib', models.BigIntegerField(blank=True, null=True)),
                ('reason', models.CharField(max_length=64)),
                ('samples', models.PositiveIntegerField(default=1)),
                ('first_seen_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField(db_index=True)),
                ('last_body_digest', models.CharField(max_length=64)),
            ],
            options={
                'ordering': ['-last_seen_at'],
                'constraints': [models.UniqueConstraint(fields=('vm_id', 'node_id_hex', 'flavor'), name='telemetry_guest_resource_shortfall_unique')],
            },
        ),
    ]
