# Generated by Django 5.2.15 on 2026-10-05 07:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("telemetry", "0010_guest_resources"),
    ]

    operations = [
        migrations.AddField(
            model_name="vmliveattestation",
            name="components_health",
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="vmliveattestation",
            name="components_instance",
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="vmliveattestation",
            name="components_release_version",
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="vmliveattestation",
            name="components_security_epoch",
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="vmliveattestation",
            name="components_unhealthy_ticks",
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
    ]
