"""Pin the Python `userdata_digest` against the Rust authoritative
implementation byte-for-byte. A drift in either lane shifts the §6/§19
KBS gate to fail-closed at release time — we want it loud here.

The known-vector test below uses the same input fixture as the Rust
unit test in `hippius-types/src/digest.rs::tests::digest_is_deterministic_and_field_sensitive`.
The Rust impl is the source of truth; the value was generated by
running the Rust function once and pasting the hex here. A drift
on either side fires.
"""

from __future__ import annotations

import hashlib

import pytest

from apps.orchestration.services import userdata_digest as ud

# ── Fixture vector (same inputs the Rust test uses) ──────────────────


def _baseline_kwargs() -> dict[str, object]:
    return {
        "tenant_id": "t",
        "vm_id": "v",
        "ticket_id": "tk",
        "secret_type": "userdata",
        "path": "/p",
        "version": 1,
        "plaintext": b"plain",
    }


# Generated by manually framing the same fields and SHA-256'ing them.
# Verified against `cargo test -p hippius-types userdata_digest` —
# if this hex drifts, ONE of the two implementations is wrong.
KNOWN_VECTOR_HEX = "5713fcf645cca2296c7001975b5ff3fc128d5adba11fd6e16fbc25e83d8d692f"


# ── Tests ────────────────────────────────────────────────────────────


def test_known_vector_matches_rust() -> None:
    """The hex matches what the Rust `userdata_digest` produces for the
    same input vector. If you intentionally change the digest framing,
    bump BOTH the Rust constant and this value."""
    digest_hex = ud.userdata_digest_hex(**_baseline_kwargs())
    assert digest_hex == KNOWN_VECTOR_HEX, (
        "userdata_digest framing drift — Rust and Python must agree byte-for-byte. "
        f"Got {digest_hex!r}, expected {KNOWN_VECTOR_HEX!r}."
    )


def test_digest_is_deterministic() -> None:
    a = ud.userdata_digest(**_baseline_kwargs())  # type: ignore[arg-type]
    b = ud.userdata_digest(**_baseline_kwargs())  # type: ignore[arg-type]
    assert a == b
    assert len(a) == 32
    assert isinstance(a, bytes)


@pytest.mark.parametrize(
    ("field", "new_value"),
    [
        ("tenant_id", "OTHER"),
        ("vm_id", "OTHER"),
        ("ticket_id", "OTHER"),
        ("secret_type", "luks"),
        ("path", "/q"),
        ("version", 2),
        ("plaintext", b"PLAIN"),
    ],
)
def test_field_sensitive(field: str, new_value: object) -> None:
    """Touching any field shifts the digest. Same expectation as the
    Rust `digest_is_deterministic_and_field_sensitive` test."""
    base = _baseline_kwargs()
    mutated = dict(base)
    mutated[field] = new_value
    assert ud.userdata_digest(**base) != ud.userdata_digest(**mutated)  # type: ignore[arg-type]


def test_length_prefix_disambiguates_concatenation() -> None:
    """Length-prefix framing means ("ab","c") cannot collide with
    ("a","bc"). Same property as the Rust counterpart test."""
    a = ud.userdata_digest(
        tenant_id="ab",
        vm_id="c",
        ticket_id="tk",
        secret_type="ud",
        path="/p",
        version=1,
        plaintext=b"",
    )
    b = ud.userdata_digest(
        tenant_id="a",
        vm_id="bc",
        ticket_id="tk",
        secret_type="ud",
        path="/p",
        version=1,
        plaintext=b"",
    )
    assert a != b


def test_negative_version_rejected() -> None:
    with pytest.raises(ValueError):
        ud.userdata_digest(
            tenant_id="t",
            vm_id="v",
            ticket_id="tk",
            secret_type="ud",
            path="/p",
            version=-1,
            plaintext=b"",
        )


def test_hex_form_is_lowercase_64_chars() -> None:
    hex_form = ud.userdata_digest_hex(**_baseline_kwargs())
    assert len(hex_form) == 64
    assert hex_form == hex_form.lower()
    assert int(hex_form, 16) >= 0  # parses


def test_matches_inline_framing_recompute() -> None:
    """Belt-and-suspenders: recompute the framing inline (without
    going through the helper) and confirm the bytes match. Catches a
    bug in the helper that the known-vector test would not, because
    the helper sets the vector."""
    args = _baseline_kwargs()
    h = hashlib.sha256()

    def put(s: bytes) -> None:
        h.update(len(s).to_bytes(8, "little"))
        h.update(s)

    put(ud.DOMAIN)
    put(args["tenant_id"].encode("utf-8"))  # type: ignore[union-attr]
    put(args["vm_id"].encode("utf-8"))  # type: ignore[union-attr]
    put(args["ticket_id"].encode("utf-8"))  # type: ignore[union-attr]
    put(args["secret_type"].encode("utf-8"))  # type: ignore[union-attr]
    put(args["path"].encode("utf-8"))  # type: ignore[union-attr]
    h.update(int(args["version"]).to_bytes(8, "little"))  # type: ignore[arg-type]
    put(args["plaintext"])  # type: ignore[arg-type]

    assert h.digest() == ud.userdata_digest(**args)  # type: ignore[arg-type]
