"""PR-S2: KBS audit-chain verifier tests.

Three layers of coverage:

  1. Cross-implementation witness: load the committed Rust-produced
     fixture (`tests/fixtures/audit_known_good`, generated by
     `cargo run --example audit_fixture`) and confirm the Python
     verifier accepts it and returns the same head.
  2. Happy path on a Python-built chain — same canonical-CBOR rules.
  3. Tamper detection: every check Rust `walk_log` enforces must also
     trip in Python. One test per failure mode.
"""

from __future__ import annotations

import binascii
import hashlib
from pathlib import Path

import cbor2
import pytest

from sentinel.tools.kbs_audit import (
    AUDIT_DOMAIN,
    HEAD_FILENAME,
    LOG_FILENAME,
    AuditVerifyError,
    read_tail,
    verify_chain,
    walk_log,
)
from tests._audit_builder import _build_record, build_chain, rewrite_log

FIXTURE_DIR = (
    Path(__file__).resolve().parent / "fixtures" / "audit_known_good"
)

KNOWN_GOOD_HEAD_HEX = "91618847234bef2d3ffb02015fbafd49300f18af36d2f2502d17dbf81208d639"


# ---------------------------------------------------------------------------
# Cross-impl: Rust fixture
# ---------------------------------------------------------------------------


def test_walks_rust_produced_fixture() -> None:
    """The Rust `cargo run --example audit_fixture` output verifies cleanly."""

    v = verify_chain(FIXTURE_DIR)
    assert v.records == 3
    assert v.head.hex() == KNOWN_GOOD_HEAD_HEX


def test_read_tail_against_rust_fixture_returns_records_in_order() -> None:
    records = read_tail(10, dir_=FIXTURE_DIR)
    assert [r.seq for r in records] == [0, 1, 2]
    assert [r.ticket_id for r in records] == ["tk-0001", "tk-0002", "tk-0003"]
    assert [r.vm_id for r in records] == ["vm-a", "vm-b", "vm-c"]
    assert [r.granted for r in records] == [True, False, True]
    assert records[0].prev_hash == bytes(32)
    # Last record's body SHA matches the head — the recomputed chain
    # tail is the same as `head.sha256`.
    assert records[-1].body_sha256.hex() == KNOWN_GOOD_HEAD_HEX


def test_read_tail_caps_at_n_argument(tmp_path: Path) -> None:
    build_chain(tmp_path)
    assert len(read_tail(1, dir_=tmp_path)) == 1
    assert len(read_tail(2, dir_=tmp_path)) == 2
    assert len(read_tail(99, dir_=tmp_path)) == 3
    assert read_tail(0, dir_=tmp_path) == []


# ---------------------------------------------------------------------------
# Happy path on Python-built chains
# ---------------------------------------------------------------------------


def test_empty_directory_verifies_as_zero_records(tmp_path: Path) -> None:
    v = verify_chain(tmp_path)
    assert v.records == 0
    assert v.head == bytes(32)


def test_python_built_chain_verifies(tmp_path: Path) -> None:
    appended = build_chain(tmp_path)
    v = verify_chain(tmp_path)
    assert v.records == len(appended)
    assert v.head == appended[-1].hash_


# ---------------------------------------------------------------------------
# Tamper detection — one test per Rust `walk_log` check
# ---------------------------------------------------------------------------


def test_tampered_body_detected(tmp_path: Path) -> None:
    """Flipping a single body byte breaks SHA256(body) == on-disk hash."""

    out = build_chain(tmp_path)
    log_path = tmp_path / LOG_FILENAME
    content = log_path.read_text()
    # Swap one hex char in the first body, leaving the hash field
    # untouched. SHA256 mismatch detected first.
    seq0, body0, hash0 = content.split("\n")[0].split(":", 2)
    flipped_body = ("0" if body0[10] != "0" else "1") + body0[1:]
    tampered = f"{seq0}:{flipped_body}:{hash0}\n" + "\n".join(content.split("\n")[1:])
    log_path.write_text(tampered)
    # Any tamper detection path is acceptable here — depending on which
    # nibble flipped, the byte may break the SHA, the CBOR decode, the
    # canonical re-encode, or the strict schema. Any AuditVerifyError
    # proves the line was rejected.
    with pytest.raises(AuditVerifyError):
        verify_chain(tmp_path)
    # Sanity: the untouched chain produces a non-empty head.
    assert out[-1].hash_ != bytes(32)


def test_swapped_records_detected_via_prev_hash(tmp_path: Path) -> None:
    """Reordering two records breaks the prev_hash chain."""

    build_chain(tmp_path)
    log_path = tmp_path / LOG_FILENAME
    lines = log_path.read_text().splitlines()
    swapped = "\n".join([lines[1], lines[0], *lines[2:]]) + "\n"
    log_path.write_text(swapped)
    with pytest.raises(AuditVerifyError, match="seq|chain broken"):
        verify_chain(tmp_path)


def test_wrong_domain_in_body_rejected(tmp_path: Path) -> None:
    """A canonical-CBOR body with the wrong domain string is rejected."""

    build_chain(
        tmp_path,
        records=[
            {
                "granted": True,
                "ticket_id": "tk",
                "vm_id": "vm",
                "reason": "ok",
                "now_unix": 100,
                "domain": "NOT_THE_AUDIT_DOMAIN",
            }
        ],
    )
    with pytest.raises(AuditVerifyError, match="wrong domain"):
        verify_chain(tmp_path)


def test_non_canonical_cbor_rejected(tmp_path: Path) -> None:
    """Indefinite-length map encoding is rejected by the canonical check."""

    body = _build_record(
        prev_hash=bytes(32),
        seq=0,
        granted=True,
        ticket_id="tk",
        vm_id="vm",
        reason="ok",
        now_unix=100,
    )
    # Replace the leading definite-length map header (0xa8 = map(8)) with
    # the indefinite-length marker (0xbf) and append a break byte (0xff).
    assert body[0] == 0xA8
    noncanon = bytes([0xBF]) + body[1:] + bytes([0xFF])
    # The non-canonical body decodes to the same value but encodes to
    # different bytes — exactly what `assert_canonical` rejects.
    assert cbor2.loads(noncanon) == cbor2.loads(body)
    h = hashlib.sha256(noncanon).digest()
    line = f"0:{binascii.hexlify(noncanon).decode()}:{binascii.hexlify(h).decode()}\n"
    rewrite_log(tmp_path, [line], head=h)
    with pytest.raises(AuditVerifyError, match="non-canonical"):
        verify_chain(tmp_path)


def test_log_missing_with_nonzero_head_is_tamper(tmp_path: Path) -> None:
    """If audit.log is deleted but head.sha256 still references records → tamper."""

    build_chain(tmp_path)
    (tmp_path / LOG_FILENAME).unlink()
    # head.sha256 left intact, pointing at a hash we can no longer prove.
    with pytest.raises(AuditVerifyError, match="missing"):
        verify_chain(tmp_path)


def test_empty_log_with_nonzero_head_is_tamper(tmp_path: Path) -> None:
    """Truncating audit.log to empty while head.sha256 is set is tamper."""

    build_chain(tmp_path)
    (tmp_path / LOG_FILENAME).write_text("")
    with pytest.raises(AuditVerifyError, match="empty"):
        verify_chain(tmp_path)


def test_head_sha256_disagrees_with_walk_is_tamper(tmp_path: Path) -> None:
    """An attacker who patches head.sha256 to a fake value is detected."""

    out = build_chain(tmp_path)
    fake_head = bytes([b ^ 0x01 for b in out[-1].hash_])
    (tmp_path / HEAD_FILENAME).write_bytes(fake_head)
    with pytest.raises(AuditVerifyError, match="head.sha256 disagrees"):
        verify_chain(tmp_path)


def test_seq_skip_detected(tmp_path: Path) -> None:
    """A line whose body seq doesn't match its position fails verification."""

    # Build a 2-record chain, then forge record 0 with body seq=5
    # but keep its line seq=0. The body-seq vs line-seq check trips.
    forged_body = _build_record(
        prev_hash=bytes(32),
        seq=5,
        granted=True,
        ticket_id="tk",
        vm_id="vm",
        reason="ok",
        now_unix=100,
    )
    h = hashlib.sha256(forged_body).digest()
    line = f"0:{binascii.hexlify(forged_body).decode()}:{binascii.hexlify(h).decode()}\n"
    rewrite_log(tmp_path, [line], head=h)
    with pytest.raises(AuditVerifyError, match="body seq|seq"):
        verify_chain(tmp_path)


def test_extra_field_in_body_rejected(tmp_path: Path) -> None:
    """A record body with an extra field is rejected by the strict schema."""

    bad = cbor2.dumps(
        {
            "domain": AUDIT_DOMAIN,
            "granted": True,
            "now_unix": 100,
            "prev_hash": bytes(32),
            "reason": "ok",
            "seq": 0,
            "ticket_id": "tk",
            "vm_id": "vm",
            "extra_field": "oops",
        },
        canonical=True,
    )
    h = hashlib.sha256(bad).digest()
    line = f"0:{binascii.hexlify(bad).decode()}:{binascii.hexlify(h).decode()}\n"
    rewrite_log(tmp_path, [line], head=h)
    with pytest.raises(AuditVerifyError, match="schema mismatch"):
        verify_chain(tmp_path)


def test_malformed_line_rejected(tmp_path: Path) -> None:
    """A line missing the body/hash separators fails parsing."""

    (tmp_path / LOG_FILENAME).write_text("0:not-a-real-line\n")
    (tmp_path / HEAD_FILENAME).write_bytes(bytes(32))
    with pytest.raises(AuditVerifyError):
        verify_chain(tmp_path)


def test_walk_log_handles_missing_directory(tmp_path: Path) -> None:
    """walk_log on a fresh directory with no log + no head returns zero."""

    v = walk_log(tmp_path)
    assert v.records == 0
    assert v.head == bytes(32)


def test_record_to_jsonable_redacts_secret_in_free_text() -> None:
    """PR-S6: audit free text crossing to the LLM is scrubbed."""

    from sentinel.tools.kbs_audit import _record_to_jsonable
    from tests._analytics_helpers import make_audit_record

    rec = make_audit_record(
        reason="denied: leaked AKIAIOSFODNN7EXAMPLE in request",
        ticket_id="tk-4471",
        vm_id="vm-9920",
    )
    out = _record_to_jsonable(rec)
    # The secret shape is gone …
    assert "AKIA" not in out["reason"]
    assert "[REDACTED]" in out["reason"]
    # … but ordinary operational ids pass through untouched.
    assert out["ticket_id"] == "tk-4471"
    assert out["vm_id"] == "vm-9920"
