# Generated by Django 5.2.15 on 2026-06-15 16:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
        ('orchestration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaunchJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_id', models.CharField(max_length=64, unique=True)),
                ('vm_id', models.CharField(db_index=True, max_length=256)),
                ('tenant_id', models.CharField(db_index=True, max_length=256)),
                ('flavor', models.CharField(max_length=32)),
                ('spec_json', models.JSONField(default=dict)),
                ('userdata_vault_path', models.CharField(max_length=512)),
                ('userdata_vault_version', models.BigIntegerField()),
                ('kek_vault_path', models.CharField(max_length=512)),
                ('state', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='queued', max_length=32)),
                ('result_json', models.JSONField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, default='', max_length=256)),
                ('miner_id', models.CharField(blank=True, default='', max_length=64)),
                ('placement_id', models.CharField(blank=True, default='', max_length=64)),
                ('phase_started_at', models.DateTimeField()),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('decided_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='launch_jobs', to='identity.serviceclient')),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['state'], name='orchestrati_state_e7ce03_idx'), models.Index(fields=['vm_id', 'state'], name='orchestrati_vm_id_3c776f_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('state__in', ['succeeded', 'failed']), _negated=True), fields=('vm_id',), name='orchestration_one_active_launch_per_vm'), models.CheckConstraint(condition=models.Q(models.Q(('state__in', ['succeeded', 'failed']), _negated=True), ('finished_at__isnull', False), _connector='OR'), name='orchestration_launch_terminal_finished')],
            },
        ),
    ]
