# Generated by Django 5.2.15 on 2026-06-30 14:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestration', '0002_launchjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementLedger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vm_id', models.CharField(db_index=True, max_length=256)),
                ('launch_digest_hex', models.CharField(db_index=True, max_length=96)),
                ('platform_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('node_id', models.CharField(blank=True, default='', max_length=64)),
                ('allowlist_epoch', models.BigIntegerField()),
                ('allowlist_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('pinned_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-pinned_at'],
            },
        ),
    ]
