# Generated by Django 5.2.15 on 2026-06-30 15:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestration', '0003_measurement_ledger'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event', models.CharField(db_index=True, max_length=64)),
                ('job_id', models.CharField(db_index=True, max_length=64)),
                ('vm_id', models.CharField(blank=True, default='', max_length=256)),
                ('payload', models.JSONField()),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=8)),
                ('next_attempt_at', models.DateTimeField(db_index=True)),
                ('last_status', models.IntegerField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, default='', max_length=256)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['next_attempt_at'],
                'indexes': [models.Index(fields=['state', 'next_attempt_at'], name='orchestrati_state_e97c05_idx')],
            },
        ),
    ]
