# Generated by Django 5.2.15 on 2026-07-09 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestration', '0004_webhook_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='launchjob',
            name='phase',
            field=models.CharField(blank=True, choices=[('queued', 'Queued'), ('staging', 'Staging secrets'), ('placing', 'Placing'), ('dispatching', 'Dispatching'), ('launched', 'Launched'), ('failed', 'Failed')], default='', max_length=16),
        ),
    ]
