# Generated by Django 5.2.15 on 2026-07-23 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifecycle', '0006_vm_netbird_ip'),
        ('orchestration', '0005_launchjob_phase'),
    ]

    operations = [
        migrations.CreateModel(
            name='RebootRecovery',
            fields=[
                ('vm', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='reboot_recovery', serialize=False, to='lifecycle.vm')),
                ('consecutive_down', models.PositiveIntegerField(default=0)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('last_outcome', models.CharField(blank=True, default='', max_length=64)),
                ('last_relaunch_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
