# Generated by Django 5.2.15 on 2026-07-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestration', '0006_rebootrecovery'),
    ]

    operations = [
        migrations.AddField(
            model_name='rebootrecovery',
            name='seen_running',
            field=models.BooleanField(default=False),
        ),
    ]
