# Generated by Django 5.2.15 on 2026-07-28 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestration', '0007_rebootrecovery_seen_running'),
    ]

    operations = [
        migrations.AddField(
            model_name='migrationjob',
            name='snapshot_state_key',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
