# Generated by Django 5.2.15 on 2026-08-12 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestration', '0008_migration_state_disk_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementledger',
            name='measurement_class',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
