# Generated by Django 5.2.15 on 2026-09-24 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestration', '0013_migration_strand_recovery'),
    ]

    operations = [
        migrations.AddField(
            model_name='decommissionjob',
            name='erase_host',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='decommissionjob',
            name='kek_erased_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
