# Generated by Django 5.2.17 on 2026-09-25 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestration', '0014_decommission_erase_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='migrationjob',
            name='snapshot_part_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='migrationjob',
            name='snapshot_part_size',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='migrationjob',
            name='snapshot_upload_id',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
    ]
