# Generated by Django 5.2.17 on 2026-09-25 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestration', '0015_migration_snapshot_multipart'),
    ]

    operations = [
        migrations.AddField(
            model_name='migrationjob',
            name='snapshot_sha256',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='migrationjob',
            name='snapshot_size',
            field=models.BigIntegerField(default=0),
        ),
    ]
