# Generated by Django 5.2.17 on 2026-09-25 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestration', '0016_migration_snapshot_digest'),
    ]

    operations = [
        migrations.AddField(
            model_name='migrationjob',
            name='snapshot_deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
