# Generated by Django 5.2.15 on 2026-09-24 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0004_servicetoken_expires_at_required'),
        ('lifecycle', '0013_zombie_observation'),
        ('orchestration', '0017_migration_snapshot_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='decommissionjob',
            name='kbs_fence',
            field=models.CharField(blank=True, choices=[('', 'Not attempted'), ('fenced', 'Fenced'), ('tombstoned', 'Tombstoned'), ('pending', 'Pending'), ('conflict', 'Conflict')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='decommissionjob',
            name='kbs_fence_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='decommissionjob',
            index=models.Index(fields=['kbs_fence'], name='orchestrati_kbs_fen_1fdefc_idx'),
        ),
    ]
