# Generated by Django 5.2.17 on 2026-09-25 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestration', '0018_decommission_kbs_fence'),
    ]

    operations = [
        migrations.AddField(
            model_name='migrationjob',
            name='cold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='migrationjob',
            name='cold_settle_reason',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='migrationjob',
            name='cold_settled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='migrationjob',
            name='failed_from_state',
            field=models.CharField(blank=True, choices=[('source_starting', 'Source starting'), ('draining', 'Draining'), ('quiescing', 'Quiescing'), ('snapshotting', 'Snapshotting'), ('uploading', 'Uploading'), ('fencing', 'Fencing'), ('awaiting_source_ack', 'Awaiting source ack'), ('dest_activating', 'Dest activating'), ('done', 'Done'), ('failed', 'Failed')], default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='migrationjob',
            name='state',
            field=models.CharField(choices=[('source_starting', 'Source starting'), ('draining', 'Draining'), ('quiescing', 'Quiescing'), ('snapshotting', 'Snapshotting'), ('uploading', 'Uploading'), ('fencing', 'Fencing'), ('awaiting_source_ack', 'Awaiting source ack'), ('dest_activating', 'Dest activating'), ('done', 'Done'), ('failed', 'Failed')], default='draining', max_length=32),
        ),
    ]
