# Generated by Django 5.2.17 on 2026-09-27 04:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0003_backup_run_poll_misses'),
        ('identity', '0004_servicetoken_expires_at_required'),
        ('orchestration', '0019_cold_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='migrationjob',
            name='kind',
            field=models.CharField(choices=[('migrate', 'Migrate'), ('restore', 'Restore'), ('failover', 'Failover')], default='migrate', max_length=16),
        ),
        migrations.AddField(
            model_name='migrationjob',
            name='prior_power_state',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='migrationjob',
            name='request_id',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='migrationjob',
            name='restore_bytes_done',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='migrationjob',
            name='restore_bytes_total',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='migrationjob',
            name='restore_cleanup_pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='migrationjob',
            name='restore_dispatched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='migrationjob',
            name='restore_dispatches',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='migrationjob',
            name='restore_eta_s',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='migrationjob',
            name='restore_id',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='migrationjob',
            name='restore_keep_original_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='migrationjob',
            name='restore_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='restore_jobs', to='backup.backuprun'),
        ),
        migrations.AddField(
            model_name='migrationjob',
            name='reverted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='migrationjob',
            name='failed_from_state',
            field=models.CharField(blank=True, choices=[('source_starting', 'Source starting'), ('draining', 'Draining'), ('quiescing', 'Quiescing'), ('snapshotting', 'Snapshotting'), ('uploading', 'Uploading'), ('fencing', 'Fencing'), ('awaiting_source_ack', 'Awaiting source ack'), ('dest_activating', 'Dest activating'), ('done', 'Done'), ('failed', 'Failed'), ('restore_staging', 'Restore staging'), ('restore_stopping', 'Restore stopping'), ('restore_verifying', 'Restore verifying'), ('restore_reverting', 'Restore reverting')], default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='migrationjob',
            name='state',
            field=models.CharField(choices=[('source_starting', 'Source starting'), ('draining', 'Draining'), ('quiescing', 'Quiescing'), ('snapshotting', 'Snapshotting'), ('uploading', 'Uploading'), ('fencing', 'Fencing'), ('awaiting_source_ack', 'Awaiting source ack'), ('dest_activating', 'Dest activating'), ('done', 'Done'), ('failed', 'Failed'), ('restore_staging', 'Restore staging'), ('restore_stopping', 'Restore stopping'), ('restore_verifying', 'Restore verifying'), ('restore_reverting', 'Restore reverting')], default='draining', max_length=32),
        ),
        migrations.CreateModel(
            name='DestAuthorization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('migrate', 'Migrate'), ('restore', 'Restore'), ('failover', 'Failover')], max_length=16)),
                ('request_id', models.CharField(max_length=128)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dest_authorizations', to='identity.serviceclient')),
            ],
        ),
        migrations.AddField(
            model_name='migrationjob',
            name='authorization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='orchestration.destauthorization'),
        ),
    ]
