# Generated by Django 5.2.17 on 2026-09-27 05:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestration', '0020_restore_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailoverQuarantine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('miner_id', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cleared_at', models.DateTimeField(blank=True, null=True)),
                ('cleared_by', models.CharField(blank=True, default='', max_length=128)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='failover_quarantines', to='orchestration.migrationjob')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('job',), name='orchestration_one_failover_quarantine_per_job')],
            },
        ),
    ]
