# Generated by Django 5.2.17 on 2026-09-28 01:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0004_backup_run_rollback_checkpoint'),
        ('lifecycle', '0017_vm_power_state_off'),
        ('orchestration', '0021_failover_quarantine'),
    ]

    operations = [
        migrations.AddField(
            model_name='destauthorization',
            name='accept_rollback',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='destauthorization',
            name='on_behalf_of_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='destauthorization',
            name='on_behalf_of_kind',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='migrationjob',
            name='original_checkpoint',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='migrationjob',
            name='original_manifest',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='migrationjob',
            name='undo',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='migrationjob',
            name='failed_from_state',
            field=models.CharField(blank=True, choices=[('source_starting', 'Source starting'), ('draining', 'Draining'), ('quiescing', 'Quiescing'), ('snapshotting', 'Snapshotting'), ('uploading', 'Uploading'), ('fencing', 'Fencing'), ('awaiting_source_ack', 'Awaiting source ack'), ('dest_activating', 'Dest activating'), ('done', 'Done'), ('failed', 'Failed'), ('restore_staging', 'Restore staging'), ('restore_stopping', 'Restore stopping'), ('restore_verifying', 'Restore verifying'), ('restore_reverting', 'Restore reverting'), ('restore_undoing', 'Restore undoing')], default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='migrationjob',
            name='state',
            field=models.CharField(choices=[('source_starting', 'Source starting'), ('draining', 'Draining'), ('quiescing', 'Quiescing'), ('snapshotting', 'Snapshotting'), ('uploading', 'Uploading'), ('fencing', 'Fencing'), ('awaiting_source_ack', 'Awaiting source ack'), ('dest_activating', 'Dest activating'), ('done', 'Done'), ('failed', 'Failed'), ('restore_staging', 'Restore staging'), ('restore_stopping', 'Restore stopping'), ('restore_verifying', 'Restore verifying'), ('restore_reverting', 'Restore reverting'), ('restore_undoing', 'Restore undoing')], default='draining', max_length=32),
        ),
        migrations.CreateModel(
            name='RollbackEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purpose', models.CharField(choices=[('restore', 'Restore'), ('undo', 'Undo')], default='restore', max_length=16)),
                ('restore_id', models.CharField(max_length=32)),
                ('from_boot_counter', models.BigIntegerField(blank=True, null=True)),
                ('to_boot_counter', models.BigIntegerField()),
                ('point_taken_at', models.DateTimeField()),
                ('manifest_sha256', models.CharField(max_length=64)),
                ('requested_by_kind', models.CharField(max_length=16)),
                ('requested_by_id', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('arm_requested_at', models.DateTimeField(blank=True, null=True)),
                ('armed_at', models.DateTimeField(blank=True, null=True)),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
                ('disarmed_at', models.DateTimeField(blank=True, null=True)),
                ('outcome', models.CharField(choices=[('pending', 'Pending'), ('armed', 'Armed'), ('committed', 'Committed'), ('committed-unverified', 'Committed (unverified)'), ('refused', 'Refused'), ('abandoned', 'Abandoned')], default='pending', max_length=24)),
                ('reason', models.CharField(blank=True, default='', max_length=256)),
                ('kbs_record', models.JSONField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rollback_events', to='orchestration.migrationjob')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rollback_events', to='backup.backuprun')),
                ('vm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rollback_events', to='lifecycle.vm')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['vm', 'arm_requested_at'], name='orchestrati_vm_id_5bec39_idx')],
                'constraints': [models.UniqueConstraint(fields=('job', 'purpose'), name='orchestration_one_rollback_per_job_purpose')],
            },
        ),
    ]
