# Generated by Django 5.2.17 on 2026-09-28 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestration', '0022_rollback_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='KbsAuditCursor',
            fields=[
                ('log', models.CharField(choices=[('release', 'Release decisions'), ('admin', 'Admin operations')], max_length=16, primary_key=True, serialize=False)),
                ('kbs_epoch', models.CharField(max_length=64)),
                ('last_seq', models.BigIntegerField()),
                ('last_hash', models.CharField(max_length=64)),
                ('broken_at_seq', models.BigIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='KbsAuditAnomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.CharField(choices=[('release', 'Release decisions'), ('admin', 'Admin operations')], max_length=16)),
                ('kbs_epoch', models.CharField(max_length=64)),
                ('kind', models.CharField(max_length=32)),
                ('seq', models.BigIntegerField()),
                ('observed', models.CharField(blank=True, default='', max_length=64)),
                ('detail', models.CharField(blank=True, default='', max_length=256)),
                ('count', models.PositiveIntegerField(default=1)),
                ('first_seen_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['first_seen_at'],
                'constraints': [models.UniqueConstraint(fields=('log', 'kbs_epoch', 'kind', 'seq', 'observed'), name='kbs_audit_anomaly_unique')],
            },
        ),
        migrations.CreateModel(
            name='KbsAuditEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.CharField(choices=[('release', 'Release decisions'), ('admin', 'Admin operations')], max_length=16)),
                ('kbs_epoch', models.CharField(max_length=64)),
                ('seq', models.BigIntegerField()),
                ('body_cbor', models.BinaryField()),
                ('sha256', models.CharField(max_length=64)),
                ('prev_hash', models.CharField(max_length=64)),
                ('fetched_at', models.DateTimeField()),
                ('chain_ok', models.BooleanField(db_index=True, default=True)),
                ('chain_error', models.CharField(blank=True, default='', max_length=256)),
                ('event_unix', models.BigIntegerField(blank=True, null=True)),
                ('op', models.CharField(blank=True, default='', max_length=64)),
                ('vm_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('ticket_id', models.CharField(blank=True, default='', max_length=128)),
                ('reason', models.CharField(blank=True, default='', max_length=128)),
                ('granted', models.BooleanField(blank=True, null=True)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('applied', models.BooleanField(blank=True, null=True)),
                ('peer_san', models.CharField(blank=True, default='', max_length=256)),
            ],
            options={
                'ordering': ['log', 'fetched_at', 'seq'],
                'indexes': [models.Index(fields=['vm_id', 'event_unix'], name='orchestrati_vm_id_bb8103_idx'), models.Index(fields=['log', 'event_unix'], name='orchestrati_log_7943b9_idx')],
                'constraints': [models.UniqueConstraint(fields=('log', 'kbs_epoch', 'seq'), name='kbs_audit_entry_unique_seq')],
            },
        ),
    ]
