# Generated by Django 5.2.15 on 2026-10-03 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestration', '0026_resizejob'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementledger',
            name='accepts_memory_eagerly',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name='measurementledger',
            name='attests_resources',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name='measurementledger',
            name='flavor',
            field=models.CharField(blank=True, db_default='', default='', max_length=32),
        ),
        migrations.AddField(
            model_name='measurementledger',
            name='launched_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
