# Generated by Django 5.2.15 on 2026-10-04 07:53

from django.db import migrations, models


def forget_unverified_launch_stamps(apps, schema_editor):
    """`launched_at` written before this migration came from code that also
    stamped a launch the miner answered `already-launched` (nothing new ran).
    From here on the stamp decides which launch is current and which are
    evicted, so an unverified one is dropped: such a VM keeps every
    measurement it pinned (as before #1374) until its next accepted launch
    stamps a trustworthy one."""
    ledger = apps.get_model("orchestration", "MeasurementLedger")
    ledger.objects.filter(launched_at__isnull=False).update(launched_at=None)


class Migration(migrations.Migration):

    dependencies = [
        ('orchestration', '0027_measurement_ledger_launch_facts'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementledger',
            name='evicted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='measurementledger',
            name='evicted_epoch',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
        migrations.RunPython(forget_unverified_launch_stamps, migrations.RunPython.noop),
    ]
