# Generated by Django 5.2.15 on 2026-10-04 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestration', '0028_measurement_ledger_evicted'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementledger',
            name='superseded_at_register',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
