# Generated by Django 5.2.15 on 2026-10-05 03:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0004_servicetoken_expires_at_required"),
        ("lifecycle", "0020_vm_guardian_wait"),
        ("orchestration", "0029_measurement_ledger_superseded_at_register"),
    ]

    operations = [
        migrations.CreateModel(
            name="GuestComponentRelease",
            fields=[
                ("version", models.PositiveIntegerField(primary_key=True, serialize=False)),
                ("commit", models.CharField(max_length=40)),
                ("security_epoch", models.PositiveIntegerField()),
                ("squashfs_sha256", models.CharField(max_length=64)),
                ("cpio_sha256", models.JSONField(default=dict)),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
                ("withdrawn_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-version"],
            },
        ),
        migrations.CreateModel(
            name="VmGuestComponents",
            fields=[
                (
                    "vm",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        primary_key=True,
                        related_name="guest_components",
                        serialize=False,
                        to="lifecycle.vm",
                    ),
                ),
                ("required_epoch", models.PositiveIntegerField(default=0)),
                ("attested_epoch", models.PositiveIntegerField(default=0)),
                ("history", models.JSONField(default=list)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="VmTicketClock",
            fields=[
                ("vm_id", models.CharField(max_length=256, primary_key=True, serialize=False)),
                ("last_issue_time", models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="GuestInitrdBuild",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("source_bake_id", models.CharField(max_length=64)),
                ("family", models.CharField(max_length=32)),
                ("kernel_sha256", models.CharField(max_length=64)),
                ("rootfs_img_sha256", models.CharField(max_length=64)),
                ("rootfs_verity_sha256", models.CharField(max_length=64)),
                ("verity_root_hash", models.CharField(max_length=64)),
                ("base_initrd_sha256", models.CharField(max_length=64)),
                ("release_cpio_sha256", models.CharField(max_length=64)),
                ("initrd_sha256", models.CharField(max_length=64, unique=True)),
                ("s3_bucket", models.CharField(max_length=256)),
                ("s3_key_prefix", models.CharField(max_length=512, unique=True)),
                ("measurement", models.JSONField()),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
                ("withdrawn_at", models.DateTimeField(blank=True, null=True)),
                (
                    "release",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="builds",
                        to="orchestration.guestcomponentrelease",
                    ),
                ),
            ],
            options={
                "ordering": ["-registered_at"],
            },
        ),
        migrations.CreateModel(
            name="GuestUpgradeJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("job_id", models.CharField(max_length=64, unique=True)),
                ("previous_prefix", models.CharField(max_length=512)),
                ("previous_initrd_sha256", models.CharField(max_length=64)),
                ("previous_epoch", models.PositiveIntegerField(default=0)),
                ("node_id", models.CharField(max_length=64)),
                ("prior_power_state", models.CharField(max_length=16)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("stopping", "Stopping"),
                            ("launching", "Launching"),
                            ("verifying", "Verifying"),
                            ("soaking", "Soaking"),
                            ("rolling_back", "Rolling back"),
                            ("done", "Done"),
                            ("rolled_back", "Rolled back"),
                            ("failed", "Failed"),
                            ("upgrade_blocked", "Upgrade blocked"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                ("not_before", models.DateTimeField()),
                ("start_requested", models.BooleanField(default=False)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("attempted_at", models.DateTimeField(blank=True, null=True)),
                ("relaunched_at", models.DateTimeField(blank=True, null=True)),
                ("measurement_before", models.CharField(blank=True, default="", max_length=128)),
                ("recover_used", models.BooleanField(default=False)),
                ("reason", models.CharField(blank=True, default="", max_length=256)),
                ("phase_started_at", models.DateTimeField()),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveBigIntegerField(default=1)),
                (
                    "decided_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="guest_upgrade_jobs",
                        to="identity.serviceclient",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="jobs",
                        to="orchestration.guestinitrdbuild",
                    ),
                ),
                (
                    "vm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="guest_upgrade_jobs",
                        to="lifecycle.vm",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="GuestUpgradeAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("upgrade", "Upgrade"),
                            ("recover", "Recover"),
                            ("rollback", "Rollback"),
                        ],
                        max_length=16,
                    ),
                ),
                ("prefix", models.CharField(max_length=512)),
                ("initrd_sha256", models.CharField(max_length=64)),
                ("supersede", models.BooleanField(default=False)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("measurement", models.CharField(blank=True, default="", max_length=128)),
                ("outcome", models.CharField(blank=True, default="", max_length=64)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempt_rows",
                        to="orchestration.guestupgradejob",
                    ),
                ),
            ],
            options={
                "ordering": ["started_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="guestinitrdbuild",
            constraint=models.UniqueConstraint(
                fields=(
                    "release",
                    "kernel_sha256",
                    "rootfs_img_sha256",
                    "rootfs_verity_sha256",
                    "verity_root_hash",
                ),
                name="orchestration_one_guest_build_per_release_and_base",
            ),
        ),
        migrations.AddIndex(
            model_name="guestupgradejob",
            index=models.Index(fields=["state"], name="orchestrati_state_a7106f_idx"),
        ),
        migrations.AddConstraint(
            model_name="guestupgradejob",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    (
                        "state__in",
                        ["done", "rolled_back", "failed", "upgrade_blocked", "cancelled"],
                    ),
                    _negated=True,
                ),
                fields=("vm",),
                name="orchestration_one_active_guest_upgrade_per_vm",
            ),
        ),
        migrations.AddConstraint(
            model_name="guestupgradejob",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        (
                            "state__in",
                            ["done", "rolled_back", "failed", "upgrade_blocked", "cancelled"],
                        ),
                        _negated=True,
                    ),
                    ("finished_at__isnull", False),
                    _connector="OR",
                ),
                name="orchestration_guest_upgrade_terminal_finished",
            ),
        ),
    ]
