# Generated by Django 5.2.15 on 2026-10-05 05:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orchestration", "0030_guest_upgrade"),
    ]

    operations = [
        migrations.AddField(
            model_name="guestupgradeattempt",
            name="answer",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="guestupgradeattempt",
            name="answered_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="guestupgradejob",
            name="park_to",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="guestupgradejob",
            name="released_by",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="measurementledger",
            name="launch_ref",
            field=models.CharField(
                blank=True, db_default="", db_index=True, default="", max_length=64
            ),
        ),
        migrations.AddField(
            model_name="measurementledger",
            name="recomputed",
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name="guestupgradejob",
            name="state",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("stopping", "Stopping"),
                    ("launching", "Launching"),
                    ("verifying", "Verifying"),
                    ("soaking", "Soaking"),
                    ("rolling_back", "Rolling back"),
                    ("parking", "Parking"),
                    ("done", "Done"),
                    ("rolled_back", "Rolled back"),
                    ("failed", "Failed"),
                    ("upgrade_blocked", "Upgrade blocked"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=32,
            ),
        ),
    ]
