# Generated by Django 5.2.15 on 2026-10-05 07:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orchestration", "0031_guest_upgrade_parking"),
    ]

    operations = [
        migrations.AddField(
            model_name="guestcomponentrelease",
            name="health_mask",
            field=models.PositiveBigIntegerField(db_default=0, default=0),
        ),
        migrations.AddField(
            model_name="guestupgradejob",
            name="gate_instance",
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="guestupgradejob",
            name="gate_unhealthy_ticks",
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="guestupgradejob",
            name="gate_verified_at_unix",
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
    ]
