# Generated by Django 5.2.15 on 2026-10-05 11:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


def _create_lock(apps, schema_editor):  # noqa: ANN001, ARG001
    apps.get_model("orchestration", "GuestUpgradeLock").objects.get_or_create(pk=1)


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0004_servicetoken_expires_at_required"),
        ("orchestration", "0032_guest_health"),
    ]

    operations = [
        migrations.CreateModel(
            name="GuestUpgradeLock",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.AddField(
            model_name="guestupgradejob",
            name="wave",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="GuestRollout",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("rollout_id", models.CharField(max_length=64, unique=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("aborted", "Aborted"),
                            ("done", "Done"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("canary_vm_ids", models.JSONField(default=list)),
                ("scope", models.JSONField(default=dict)),
                ("waves", models.JSONField(default=list)),
                ("current_wave", models.PositiveSmallIntegerField(default=0)),
                ("members", models.JSONField(default=list)),
                ("assigned", models.JSONField(default=dict)),
                ("population", models.PositiveIntegerField(default=0)),
                ("skipped", models.JSONField(default=dict)),
                ("wave_done_at", models.DateTimeField(blank=True, null=True)),
                ("max_concurrent", models.PositiveSmallIntegerField(default=2)),
                ("wave_pause_s", models.PositiveIntegerField(default=1800)),
                ("max_failure_ratio", models.FloatField(default=0.1)),
                ("not_before", models.DateTimeField(blank=True, null=True)),
                ("paused_reason", models.CharField(blank=True, default="", max_length=256)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveBigIntegerField(default=1)),
                (
                    "decided_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="guest_rollouts",
                        to="identity.serviceclient",
                    ),
                ),
                (
                    "release",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rollouts",
                        to="orchestration.guestcomponentrelease",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="guestupgradejob",
            name="rollout",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="jobs",
                to="orchestration.guestrollout",
            ),
        ),
        migrations.RunPython(_create_lock, migrations.RunPython.noop),
    ]
