# Generated by Django 5.2.15 on 2026-10-05 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orchestration", "0033_guest_rollout"),
    ]

    operations = [
        migrations.AddField(
            model_name="guestupgradejob",
            name="outcome",
            field=models.CharField(blank=True, db_default="", default="", max_length=32),
        ),
        migrations.AddField(
            model_name="guestupgradejob",
            name="recoveries",
            field=models.JSONField(db_default=[], default=list),
        ),
        migrations.AddField(
            model_name="guestupgradejob",
            name="retry_of",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="retries",
                to="orchestration.guestupgradejob",
            ),
        ),
        migrations.AlterField(
            model_name="guestupgradeattempt",
            name="kind",
            field=models.CharField(
                choices=[
                    ("upgrade", "Upgrade"),
                    ("recover", "Recover"),
                    ("rollback", "Rollback"),
                    ("operator_start", "Operator start"),
                ],
                max_length=16,
            ),
        ),
    ]
