# Generated by Django 5.2.18 on 2026-10-09 11:00

from django.db import migrations, models


def committed_at_of_done_restores(apps, schema_editor):
    """A restore / failover past its commit point: one that reached `done`,
    or failed (or was undone) after it. Its finish is the closest instant
    on record."""
    from django.db.models import F, Q

    past_commit = (
        Q(state="done")
        | Q(reason__startswith="failed-after-commit")
        | Q(reason__startswith="undone-after-commit")
        | Q(reason__contains="revert-raced-commit:")
    )
    apps.get_model("orchestration", "MigrationJob").objects.filter(
        past_commit, kind__in=("restore", "failover"), committed_at__isnull=True
    ).exclude(finished_at__isnull=True).update(committed_at=F("finished_at"))


class Migration(migrations.Migration):

    dependencies = [
        ('orchestration', '0037_kbs_audit_cursor_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='migrationjob',
            name='committed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='migrationjob',
            name='trigger',
            field=models.CharField(db_default='operator', default='operator', max_length=16),
        ),
        migrations.RunPython(committed_at_of_done_restores, migrations.RunPython.noop),
    ]
