# Generated by Django 5.2.14 on 2026-05-22 06:09

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MinerIdentity",
            fields=[
                ("miner_id", models.CharField(max_length=64, primary_key=True, serialize=False)),
                ("pubkey_hex", models.CharField(max_length=64)),
                ("platform_id", models.CharField(db_index=True, max_length=128)),
                ("netbird_peer_id", models.CharField(blank=True, default="", max_length=64)),
                ("netbird_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("quarantined", "Quarantined")],
                        default="active",
                        max_length=16,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "miner identities",
                "ordering": ["miner_id"],
                "constraints": [
                    models.UniqueConstraint(fields=("pubkey_hex",), name="miners_unique_pubkey"),
                    models.UniqueConstraint(fields=("platform_id",), name="miners_unique_platform"),
                ],
            },
        ),
    ]
