# Generated by Django 5.2.14 on 2026-05-22 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mineridentity',
            name='last_heartbeat_sequence',
            field=models.PositiveBigIntegerField(blank=True, default=None, help_text='Monotonic sequence of the last accepted heartbeat envelope (§K / PR-Part4-B replay gate). NULL = no heartbeat received yet.', null=True),
        ),
    ]
