# Generated by Django 5.2.17 on 2026-09-25 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miners', '0004_minerlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='mineridentity',
            name='snp_generation',
            field=models.CharField(blank=True, choices=[('milan', 'Milan (EpycMilan)'), ('genoa', 'Genoa (EpycGenoa)'), ('turin', 'Turin (EpycTurin)')], db_default='', default='', help_text="SEV-SNP CPU generation, operator-registered. Selects the vCPU model of the launch-digest recompute and the §25 same-generation gate. Empty = legacy, inferred from the CHIP_ID length (8 bytes ⇒ Turin, 64 bytes ⇒ Genoa). REQUIRED for Milan: its CHIP_ID is 64 bytes like Genoa's, so an unset Milan host is measured as Genoa and every launch is refused. Must agree with the CHIP_ID length (turin = 8 bytes, genoa/milan = 64), else vali fails closed.", max_length=8),
        ),
    ]
