# Generated by Django 5.2.15 on 2026-07-22 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoldenImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=64, unique=True)),
                ('distro', models.CharField(max_length=64)),
                ('bake_id', models.CharField(max_length=64)),
                ('blessed_at', models.DateTimeField()),
                ('blessed_by', models.CharField(blank=True, default='', max_length=128)),
            ],
            options={
                'ordering': ['image_name'],
            },
        ),
    ]
