# Generated by Django 5.2.15 on 2026-10-05 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goldenimage',
            name='guest_release',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
