# Generated by Django 5.2.15 on 2026-06-29 05:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifecycle', '0002_vm_max_price_per_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoppedAckIngest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vm_id', models.CharField(db_index=True, max_length=256)),
                ('generation', models.BigIntegerField()),
                ('signed_ack', models.BinaryField()),
                ('received_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['vm_id', 'generation'], name='lifecycle_s_vm_id_f60fc3_idx')],
                'constraints': [models.UniqueConstraint(fields=('vm_id', 'generation'), name='lifecycle_stopped_ack_vm_generation_unique')],
            },
        ),
    ]
