# Generated by Django 5.2.15 on 2026-07-09 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifecycle', '0004_vm_tenant_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vm',
            name='boot_phase',
            field=models.CharField(blank=True, choices=[('booting', 'Booting'), ('kek_released', 'KEK released'), ('running', 'Running')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='vm',
            name='boot_phase_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
