# Generated by Django 5.2.15 on 2026-07-13 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifecycle', '0005_vm_boot_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='vm',
            name='netbird_ip',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
