# Generated by Django 5.2.15 on 2026-07-27 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifecycle', '0006_vm_netbird_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='vm',
            name='signing_generation',
            field=models.BigIntegerField(default=1),
        ),
    ]
