# Generated by Django 5.2.15 on 2026-08-12 23:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifecycle', '0009_vm_guest_signal'),
    ]

    operations = [
        migrations.CreateModel(
            name='VmBaseImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vm_id', models.CharField(max_length=256, unique=True)),
                ('disk_mode', models.CharField(blank=True, default='', max_length=32)),
                ('bake_id', models.CharField(blank=True, db_index=True, default='', max_length=256)),
                ('image_name', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('rootfs_img_sha256_hex', models.CharField(blank=True, default='', max_length=64)),
                ('rootfs_verity_sha256_hex', models.CharField(blank=True, default='', max_length=64)),
                ('verity_root_hash_hex', models.CharField(blank=True, default='', max_length=64)),
                ('rootfs_data_path', models.CharField(blank=True, default='', max_length=512)),
                ('rootfs_hash_path', models.CharField(blank=True, default='', max_length=512)),
                ('recorded_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['rootfs_img_sha256_hex'], name='lifecycle_base_img_idx')],
            },
        ),
    ]
