# Generated by Django 5.2.15 on 2026-08-13 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifecycle', '0010_vm_base_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='vm',
            name='launch_abandoned_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='vm',
            name='launch_abandoned_outcome',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='vm',
            name='launch_abandoned_registered',
            field=models.BooleanField(default=False),
        ),
    ]
