# Generated by Django 5.2.15 on 2026-09-24 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifecycle', '0012_vm_power_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZombieObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vm_id', models.CharField(db_index=True, max_length=64)),
                ('miner_id', models.CharField(blank=True, default='', max_length=128)),
                ('miner_node_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('attribution', models.CharField(default='peer', max_length=16)),
                ('last_kind', models.CharField(default='', max_length=32)),
                ('count', models.PositiveBigIntegerField(default=0)),
                ('first_seen_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField(db_index=True)),
                ('strong_last_seen_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('alerted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('vm_id', 'miner_id'), name='lifecycle_zombie_vm_miner_uniq')],
            },
        ),
    ]
