# Generated by Django 5.2.17 on 2026-09-25 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifecycle', '0013_zombie_observation'),
    ]

    operations = [
        migrations.AddField(
            model_name='vm',
            name='power_stop_proof',
            field=models.BinaryField(blank=True, max_length=32, null=True),
        ),
    ]
