# Generated by Django 5.2.17 on 2026-09-25 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifecycle', '0014_vm_power_stop_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='vm',
            name='netbird_peer_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.CreateModel(
            name='VmNetbirdKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setup_key_id', models.CharField(max_length=64, unique=True)),
                ('persistent', models.BooleanField()),
                ('expires_at', models.DateTimeField()),
                ('peer_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('settled_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='netbird_keys', to='lifecycle.vm')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
