# Generated by Django 5.2.15 on 2026-09-27 03:50

from django.db import migrations, models
from django.db.models import F


def destroyed_rows_off(apps, schema_editor):
    """Rows tombstoned before `off` existed still read their last power
    state (mostly `running`). `power_state_at` takes their `updated_at` —
    the best destroy time known, and what zombie.py's erase-time fallback
    read until now; it reads `power_state_at` from here on, which no later
    write moves. The historical manager does not stamp `updated_at`."""
    Vm = apps.get_model("lifecycle", "Vm")
    Vm.objects.filter(state="destroyed").exclude(power_state="off").update(
        power_state="off", power_state_at=F("updated_at"), power_stop_proof=None
    )


class Migration(migrations.Migration):

    dependencies = [
        ('lifecycle', '0016_vm_boot_started_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vm',
            name='power_state',
            field=models.CharField(choices=[('running', 'Running'), ('stopping', 'Stopping'), ('stopped', 'Stopped'), ('starting', 'Starting'), ('off', 'Off')], db_index=True, default='running', max_length=16),
        ),
        migrations.RunPython(destroyed_rows_off, migrations.RunPython.noop),
    ]
