# Generated by Django 5.2.18 on 2026-10-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifecycle', '0020_vm_guardian_wait'),
    ]

    operations = [
        migrations.AddField(
            model_name='vm',
            name='boot_phase_inferred_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
