# Generated by Django 5.2.18 on 2026-10-09 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifecycle', '0021_vm_boot_phase_inferred_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='vm',
            name='placement_group',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddIndex(
            model_name='vm',
            index=models.Index(fields=['tenant_id', 'placement_group'], name='lifecycle_v_tenant_group_idx'),
        ),
    ]
