# Generated by Django 5.2.15 on 2026-09-24 12:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lifecycle', '0012_vm_power_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupChain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('failed', 'Failed'), ('pruned', 'Pruned')], default='open', max_length=16)),
                ('boot_counter', models.BigIntegerField(blank=True, null=True)),
                ('full_bytes', models.BigIntegerField(default=0)),
                ('incremental_bytes', models.BigIntegerField(default=0)),
                ('incremental_count', models.PositiveIntegerField(default=0)),
                ('next_seq', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('pruned_at', models.DateTimeField(blank=True, null=True)),
                ('vm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_chains', to='lifecycle.vm')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BackupPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('interval_s', models.PositiveIntegerField(choices=[(86400, '24 h'), (21600, '6 h'), (3600, '1 h'), (900, '15 min')])),
                ('retention_days', models.PositiveIntegerField(default=7)),
                ('failover_mode', models.CharField(choices=[('auto', 'Automatic'), ('manual', 'Manual')], default='auto', max_length=16)),
                ('full_required', models.BooleanField(default=True)),
                ('observed_boot_counter', models.BigIntegerField(blank=True, null=True)),
                ('observed_at', models.DateTimeField(blank=True, null=True)),
                ('last_probe_at', models.DateTimeField(blank=True, null=True)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vm', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='backup_policy', to='lifecycle.vm')),
            ],
        ),
        migrations.CreateModel(
            name='BackupRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seq', models.PositiveIntegerField()),
                ('kind', models.CharField(choices=[('full', 'Full'), ('incremental', 'Incremental')], max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('reason', models.CharField(blank=True, default='', max_length=64)),
                ('miner_id', models.CharField(max_length=256)),
                ('disk_key', models.CharField(max_length=512)),
                ('state_key', models.CharField(max_length=512)),
                ('manifest_key', models.CharField(max_length=512)),
                ('upload_id', models.CharField(blank=True, default='', max_length=512)),
                ('upload_open', models.BooleanField(default=False)),
                ('parent_run_id', models.CharField(blank=True, default='', max_length=64)),
                ('part_size', models.BigIntegerField()),
                ('part_count', models.PositiveIntegerField()),
                ('disk_bytes', models.BigIntegerField(default=0)),
                ('disk_sha256_hex', models.CharField(blank=True, default='', max_length=64)),
                ('part_etags', models.JSONField(blank=True, default=list)),
                ('part_sha256_hex', models.JSONField(blank=True, default=list)),
                ('state_bytes', models.BigIntegerField(default=0)),
                ('state_sha256_hex', models.CharField(blank=True, default='', max_length=64)),
                ('boot_counter', models.BigIntegerField(blank=True, null=True)),
                ('bitmap_present', models.BooleanField(blank=True, null=True)),
                ('miner_duration_s', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='backup.backupchain')),
                ('vm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_runs', to='lifecycle.vm')),
            ],
            options={
                'ordering': ['chain', 'seq'],
            },
        ),
        migrations.AddIndex(
            model_name='backupchain',
            index=models.Index(fields=['vm', 'state'], name='backup_back_vm_id_1da91c_idx'),
        ),
        migrations.AddConstraint(
            model_name='backuprun',
            constraint=models.UniqueConstraint(fields=('chain', 'seq'), name='backup_run_chain_seq'),
        ),
        migrations.AddConstraint(
            model_name='backuprun',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'running'])), fields=('vm',), name='backup_one_active_run_per_vm'),
        ),
    ]
