# Generated by Django 5.2.15 on 2026-09-24 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupJanitorState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mpu_marker', models.JSONField(blank=True, null=True)),
                ('mpu_sweep_finished_at', models.DateTimeField(blank=True, null=True)),
                ('staging_marker', models.JSONField(blank=True, null=True)),
                ('staging_sweep_finished_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='backuprun',
            name='state_key',
            field=models.CharField(db_index=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='backuprun',
            name='upload_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=512),
        ),
    ]
