# Generated by Django 5.2.15 on 2026-09-24 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0002_janitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='backuprun',
            name='poll_misses',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
