# Generated by Django 5.2.17 on 2026-09-28 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0003_backup_run_poll_misses'),
    ]

    operations = [
        migrations.AddField(
            model_name='backuprun',
            name='kbs_checkpoint',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backuprun',
            name='manifest_json',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='backuprun',
            name='manifest_sha256',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
