# Generated by Django 5.2.18 on 2026-10-09 10:58

from django.db import migrations, models


def every_policy_manual(apps, schema_editor):
    """No customer ever chose `auto`: it was only the old default."""
    apps.get_model("backup", "BackupPolicy").objects.exclude(failover_mode="manual").update(
        failover_mode="manual"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0004_backup_run_rollback_checkpoint'),
    ]

    operations = [
        migrations.RunPython(every_policy_manual, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='backuppolicy',
            name='failover_mode',
            field=models.CharField(choices=[('auto', 'Automatic'), ('manual', 'Manual')], default='manual', max_length=16),
        ),
    ]
