# Generated by Django 5.2.15 on 2026-09-23 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lifecycle', '0012_vm_power_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngressEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=28, unique=True)),
                ('provider', models.CharField(blank=True, default='', max_length=64)),
                ('region', models.CharField(db_index=True, max_length=2)),
                ('netbird_peer_id', models.CharField(blank=True, default='', max_length=64)),
                ('netbird_ip', models.GenericIPAddressField(protocol='IPv4', unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('draining', 'Draining'), ('disabled', 'Disabled')], default='active', max_length=16)),
                ('desired_revision', models.BigIntegerField(default=1)),
                ('applied_revision', models.BigIntegerField(default=0)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_report', models.JSONField(blank=True, default=dict)),
                ('per_ip_mbps', models.PositiveIntegerField(default=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PublicIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.GenericIPAddressField(protocol='IPv4', unique=True)),
                ('state', models.CharField(choices=[('free', 'Free'), ('attached', 'Attached'), ('quarantined', 'Quarantined')], default='free', max_length=16)),
                ('target_ip', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4')),
                ('attached_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('edge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='network.ingressedge')),
                ('vm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='public_ips', to='lifecycle.vm')),
            ],
            options={
                'ordering': ['address'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('state', 'attached')), fields=('vm',), name='network_one_attached_public_ip_per_vm'), models.CheckConstraint(condition=models.Q(models.Q(('state', 'free'), ('vm__isnull', True)), models.Q(('state', 'attached'), ('vm__isnull', False)), ('state', 'quarantined'), _connector='OR'), name='network_public_ip_holder_matches_state')],
            },
        ),
    ]
