# Generated by Django 5.2.15 on 2026-09-23 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingressedge',
            name='netbird_ip',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='IPv4', unique=True),
        ),
    ]
