# Generated by Django 5.2.15 on 2026-09-24 20:39

from django.db import migrations, models


def backfill_quarantined(apps, schema_editor):
    """Addresses already in quarantine keep their previous holder in `vm`:
    record that VM's tenant, so they can go back to it like any address
    released after this migration."""
    PublicIP = apps.get_model("network", "PublicIP")
    for ip in PublicIP.objects.filter(state="quarantined", vm__isnull=False).select_related("vm"):
        if ip.vm.tenant_id:
            ip.last_tenant_id = ip.vm.tenant_id
            ip.save(update_fields=["last_tenant_id"])


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_ingressedge_unbound'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicip',
            name='last_tenant_id',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.RunPython(backfill_quarantined, migrations.RunPython.noop),
    ]
