# Generated by Django 5.2.15 on 2026-10-06 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miners', '0006_autoprovision_placeholder_per_node'),
        ('network', '0003_publicip_last_tenant_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='EgressRegion',
            fields=[
                ('region', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('local', 'Local'), ('edge', 'Edge')], default='local', max_length=8)),
                ('routing_enabled', models.BooleanField(default=False)),
                ('enforce', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['region'],
            },
        ),
        migrations.CreateModel(
            name='MinerNetPolicy',
            fields=[
                ('miner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='net_policy', serialize=False, to='miners.mineridentity')),
                ('revision', models.BigIntegerField(default=0)),
                ('content_key', models.CharField(blank=True, default='', max_length=64)),
                ('body_sha', models.CharField(blank=True, default='', max_length=64)),
                ('body', models.JSONField(blank=True, default=dict)),
                ('region', models.CharField(blank=True, default='', max_length=2)),
                ('mode', models.CharField(choices=[('local', 'Local'), ('edge', 'Edge')], default='local', max_length=8)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('acked_revision', models.BigIntegerField(default=0)),
                ('acked_sha', models.CharField(blank=True, default='', max_length=64)),
                ('acked_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, default='', max_length=256)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'miner net policies',
                'ordering': ['miner_id'],
            },
        ),
        migrations.AddField(
            model_name='ingressedge',
            name='egress_ip',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='IPv4', unique=True),
        ),
    ]
