# Generated by Django 5.2.15 on 2026-10-06 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifecycle', '0020_vm_guardian_wait'),
        ('network', '0004_egressregion_minernetpolicy'),
    ]

    operations = [
        migrations.CreateModel(
            name='VmEgressLease',
            fields=[
                ('vm', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='egress_lease', serialize=False, to='lifecycle.vm')),
                ('region', models.CharField(max_length=2)),
                ('target_ip', models.GenericIPAddressField(protocol='IPv4')),
                ('epoch', models.BigIntegerField(default=1)),
                ('class_id', models.PositiveIntegerField()),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['edge_id', 'class_id'],
            },
        ),
        migrations.AddField(
            model_name='ingressedge',
            name='egress_digest',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='publicip',
            name='epoch',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='publicip',
            name='smtp_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publicip',
            name='vm_region',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AddConstraint(
            model_name='egressregion',
            constraint=models.CheckConstraint(condition=models.Q(('region__regex', '^[A-Z]{2}$')), name='network_egress_region_alpha2_upper'),
        ),
        migrations.AddField(
            model_name='vmegresslease',
            name='edge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='egress_leases', to='network.ingressedge'),
        ),
        migrations.AddConstraint(
            model_name='vmegresslease',
            constraint=models.UniqueConstraint(fields=('edge', 'class_id'), name='network_egress_class_id_per_edge'),
        ),
        migrations.AddConstraint(
            model_name='vmegresslease',
            constraint=models.CheckConstraint(condition=models.Q(('class_id__gte', 4096), ('class_id__lte', 65535)), name='network_egress_class_id_range'),
        ),
        migrations.AddConstraint(
            model_name='vmegresslease',
            constraint=models.CheckConstraint(condition=models.Q(('region__regex', '^[A-Z]{2}$')), name='network_egress_lease_region_alpha2_upper'),
        ),
    ]
