# Generated by Django 5.2.15 on 2026-10-06 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_egress_feed'),
    ]

    operations = [
        migrations.AddField(
            model_name='minernetpolicy',
            name='apply_failures',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='minernetpolicy',
            name='edge_unsupported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
