# Generated by Django 5.2.15 on 2026-10-07 01:14

from django.db import migrations, models


# The backend refuses class id 0xffff: the range ends at 0xfffe. Numbered
# 0008 because the CDN N1 change (#1444) claims 0007.


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_net_policy_refusals'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vmegresslease',
            name='network_egress_class_id_range',
        ),
        migrations.AddConstraint(
            model_name='vmegresslease',
            constraint=models.CheckConstraint(condition=models.Q(('class_id__gte', 4096), ('class_id__lte', 65534)), name='network_egress_class_id_range'),
        ),
    ]
