# Generated by Django 5.2.15 on 2026-06-30 21:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
        ('lifecycle', '0004_vm_tenant_id'),
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceMigrationRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recommendation_id', models.CharField(max_length=64, unique=True)),
                ('current_node_id', models.CharField(db_index=True, max_length=64)),
                ('suggested_dest_node_id', models.CharField(blank=True, default='', max_length=64)),
                ('new_price', models.BigIntegerField()),
                ('ceiling', models.BigIntegerField()),
                ('effective_block', models.BigIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('dismissed', 'Dismissed'), ('superseded', 'Superseded')], default='pending', max_length=32)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='price_recommendations', to='identity.serviceclient')),
                ('vm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_recommendations', to='lifecycle.vm')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='scheduler_p_status_8650da_idx'), models.Index(fields=['current_node_id', 'status'], name='scheduler_p_current_966094_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('vm',), name='scheduler_one_pending_recommendation_per_vm'), models.CheckConstraint(condition=models.Q(('status', 'pending'), ('decided_at__isnull', False), _connector='OR'), name='scheduler_recommendation_decided_requires_decided_at')],
            },
        ),
    ]
