# Generated by Django 5.2.15 on 2026-07-01 05:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_pricemigrationrecommendation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptWatermark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vm_id', models.CharField(max_length=128)),
                ('lease_id', models.CharField(blank=True, default='', max_length=256)),
                ('last_monotonic_seq', models.BigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('vm_id', 'lease_id'), name='scheduler_receipt_watermark_unique_vm_lease')],
            },
        ),
        migrations.CreateModel(
            name='UsageAccrual',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('epoch', models.BigIntegerField()),
                ('miner_node_id', models.CharField(db_index=True, max_length=64)),
                ('vm_id', models.CharField(db_index=True, max_length=128)),
                ('resource_class', models.CharField(max_length=128)),
                ('lease_id', models.CharField(blank=True, default='', max_length=256)),
                ('unit_seconds', models.BigIntegerField(default=0)),
                ('billable_seconds', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-epoch', 'miner_node_id'],
                'indexes': [models.Index(fields=['epoch', 'miner_node_id'], name='scheduler_u_epoch_22227c_idx')],
                'constraints': [models.UniqueConstraint(fields=('epoch', 'miner_node_id', 'vm_id'), name='scheduler_usage_accrual_unique_epoch_miner_vm')],
            },
        ),
    ]
