# Generated by Django 5.2.15 on 2026-07-06 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
        ('lifecycle', '0004_vm_tenant_id'),
        ('scheduler', '0005_receiptwatermark_last_period_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='placement',
            name='owner',
            field=models.CharField(blank=True, db_index=True, default='', max_length=256),
        ),
        migrations.AddIndex(
            model_name='placement',
            index=models.Index(fields=['owner', 'miner_node_id', 'status'], name='scheduler_p_owner_f6c325_idx'),
        ),
    ]
