# Generated by Django 5.2.15 on 2026-07-20 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0006_placement_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='minercapacity',
            name='reported_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='minercapacity',
            name='reported_memory_available_mib',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='minercapacity',
            name='total_cpus',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='minercapacity',
            name='total_memory_mb',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
