# Generated by Django 5.2.15 on 2026-08-12 21:58
#
# §23/§25 — the append-only billing CUSTODY history (who is PAID for a
# VM's uptime, from when), split out of the launch-time
# `VmBillingBinding` (what the guest may DECLARE — immutable, it lives on
# the SNP-measured cmdline).
#
# The backfill below opens ONE `launch` row per existing binding at that
# binding's own `created_at`, which is exactly the attribution in force
# today: before this history existed the meter credited the receipt's
# self-declared node, which for every VM in the fleet is its launch node.
# So the migration re-attributes NOTHING — no already-accrued
# `UsageAccrual` row is touched, and no live VM's crediting changes.
# (Explicitly NOT backfilled from `Vm.host`: a VM that already migrated
# under the old code has been credited to its SOURCE, and rewriting
# history to say otherwise would be a second payments bug.)

import uuid
from django.db import migrations, models


def _open_launch_assignments(apps, schema_editor):
    VmBillingBinding = apps.get_model("scheduler", "VmBillingBinding")
    VmBillingAssignment = apps.get_model("scheduler", "VmBillingAssignment")
    rows = [
        VmBillingAssignment(
            vm_id=b.vm_id,
            node_id_hex=(b.node_id_hex or "").lower(),
            effective_from_unix=int(b.created_at.timestamp()),
            reason="launch",
        )
        for b in VmBillingBinding.objects.all().iterator()
    ]
    VmBillingAssignment.objects.bulk_create(rows, batch_size=500)


def _drop_launch_assignments(apps, schema_editor):
    # Reverse of the backfill only — the table itself is dropped by the
    # CreateModel reversal. A re-forward re-derives the same rows.
    VmBillingAssignment = apps.get_model("scheduler", "VmBillingAssignment")
    VmBillingAssignment.objects.filter(reason="launch").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0007_dynamic_capacity_trusted_hw'),
    ]

    operations = [
        migrations.CreateModel(
            name='VmBillingAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vm_id', models.CharField(db_index=True, max_length=128)),
                ('node_id_hex', models.CharField(blank=True, default='', max_length=64)),
                ('effective_from_unix', models.BigIntegerField()),
                ('reason', models.CharField(default='launch', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['vm_id', '-effective_from_unix', '-created_at'],
                'indexes': [models.Index(fields=['vm_id', 'effective_from_unix'], name='scheduler_v_vm_id_a74246_idx')],
            },
        ),
        migrations.RunPython(
            _open_launch_assignments, _drop_launch_assignments
        ),
    ]
