# Generated by Django 5.2.18 on 2026-10-07 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lifecycle', '0020_vm_guardian_wait'),
    ]

    operations = [
        migrations.CreateModel(
            name='CdnFleetKey',
            fields=[
                ('version', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('x25519_public', models.BinaryField(max_length=32)),
                ('kbs_kid_hex', models.CharField(max_length=128)),
                ('kbs_signature', models.BinaryField(max_length=64)),
                ('state', models.CharField(choices=[('pending', 'pending'), ('active', 'active'), ('retiring', 'retiring'), ('retired', 'retired')], db_index=True, max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['version'],
            },
        ),
        migrations.CreateModel(
            name='CdnRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CdnCaKey',
            fields=[
                ('kid', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('transit_key', models.CharField(max_length=64)),
                ('transit_key_version', models.PositiveIntegerField()),
                ('public_key', models.BinaryField(max_length=32)),
                ('cert_pem', models.TextField()),
                ('not_before', models.DateTimeField()),
                ('not_after', models.DateTimeField()),
                ('state', models.CharField(choices=[('pending', 'pending'), ('active', 'active'), ('retiring', 'retiring'), ('retired', 'retired')], db_index=True, max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['transit_key', 'transit_key_version'],
                'constraints': [models.UniqueConstraint(fields=('transit_key', 'transit_key_version'), name='cdn_ca_one_row_per_transit_version'), models.UniqueConstraint(condition=models.Q(('state', 'active')), fields=('state',), name='cdn_ca_one_active'), models.UniqueConstraint(condition=models.Q(('state', 'pending')), fields=('state',), name='cdn_ca_one_pending')],
            },
        ),
        migrations.CreateModel(
            name='CdnRegion',
            fields=[
                ('region', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=False)),
                ('desired_nodes', models.PositiveIntegerField(default=0)),
                ('flavor', models.CharField(default='xlarge', max_length=32)),
                ('failover_region', models.CharField(blank=True, default='', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['region'],
                'constraints': [models.CheckConstraint(condition=models.Q(('region__regex', '^[A-Z]{2}$')), name='cdn_region_alpha2_upper')],
            },
        ),
        migrations.CreateModel(
            name='CdnNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=128, unique=True)),
                ('region', models.CharField(db_index=True, max_length=2)),
                ('state', models.CharField(choices=[('launching', 'launching'), ('booting', 'booting'), ('ready', 'ready'), ('draining', 'draining'), ('drained', 'drained'), ('decommissioning', 'decommissioning'), ('failed', 'failed'), ('destroyed', 'destroyed')], db_index=True, default='launching', max_length=16)),
                ('state_changed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.CharField(blank=True, default='', max_length=256)),
                ('node_public_key', models.BinaryField(blank=True, max_length=32, null=True)),
                ('cert_pem', models.TextField(blank=True, default='')),
                ('cert_serial', models.CharField(blank=True, default='', max_length=64)),
                ('cert_not_before', models.DateTimeField(blank=True, null=True)),
                ('cert_not_after', models.DateTimeField(blank=True, null=True)),
                ('cert_generation', models.BigIntegerField(blank=True, null=True)),
                ('cert_ca_kid', models.CharField(blank=True, default='', max_length=32)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('drain_requested_at', models.DateTimeField(blank=True, null=True)),
                ('drain_reason', models.CharField(blank=True, choices=[('replace', 'replace'), ('scale_down', 'scale_down'), ('upgrade', 'upgrade'), ('rotate', 'rotate'), ('operator', 'operator')], default='', max_length=16)),
                ('dns_released_at', models.DateTimeField(blank=True, null=True)),
                ('dns_release_forced', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vm', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cdn_node', to='lifecycle.vm')),
            ],
            options={
                'ordering': ['region', 'created_at', 'node_id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('region__regex', '^[A-Z]{2}$')), name='cdn_node_region_alpha2_upper'), models.CheckConstraint(condition=models.Q(models.Q(('state__in', ['drained', 'decommissioning']), _negated=True), ('dns_released_at__isnull', False), ('ready_at__isnull', True), _connector='OR'), name='cdn_node_drained_only_after_dns_released'), models.CheckConstraint(condition=models.Q(models.Q(('state', 'ready'), _negated=True), ('ready_at__isnull', False), _connector='OR'), name='cdn_node_ready_has_ready_at')],
            },
        ),
    ]
