# Generated by Django 5.2.18 on 2026-10-07 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cdnnode',
            name='bake_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='cdnnode',
            name='dns_release_change_id',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='cdnnode',
            name='dns_release_revision_seen',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cdnnode',
            name='drain_ack_alerted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cdnnode',
            name='flavor',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='cdnnode',
            name='image_name',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='cdnnode',
            name='launch_job_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='cdnregion',
            name='launch_failed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cdnregion',
            name='launch_failures',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cdnrevision',
            name='network_digest',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
