# Generated by Django 5.2.18 on 2026-10-07 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdn', '0002_fleet_reconciler'),
    ]

    operations = [
        migrations.AddField(
            model_name='cdnrevision',
            name='liveness_hold_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cdnrevision',
            name='liveness_outage_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
