# Generated by Django 5.2.18 on 2026-10-07 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdn', '0003_liveness_hold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cdnrevision',
            name='liveness_outage_seen_at',
        ),
        migrations.AddField(
            model_name='cdnrevision',
            name='liveness_clear_passes',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='cdnfleetkey',
            constraint=models.UniqueConstraint(condition=models.Q(('state', 'active')), fields=('state',), name='cdn_fleet_one_active'),
        ),
    ]
