#!/usr/bin/env bash
# `build-ovmf.sh EDK2_TAG EDK2_COMMIT [WORKDIR]`
#
# Clones `tianocore/edk2` at `EDK2_TAG`, verifies that `HEAD` is the
# pinned `EDK2_COMMIT`, then builds `OvmfPkg/AmdSev/AmdSevX64.dsc`
# (X64, GCC, RELEASE). Outputs the resulting `OVMF.fd` at
# `/out/OVMF.fd`.
#
# Why the tag + commit pair: GitHub allows `fetch --depth 1` of a
# named ref (tag or branch) but not always of an arbitrary commit sha
# (`uploadpack.allowReachableSHA1InWant` is off by default on some
# servers). Fetching the tag works; the explicit commit-sha
# verification afterwards still pins the bytes against a server-side
# tag re-point.
#
# Runs INSIDE the Linux/amd64 trixie builder image so every host uses
# the same toolchain. The Dockerfile pins gcc/nasm/iasl/python3 by
# `=<version>`; this script pins `EDK2_TAG` + `EDK2_COMMIT` and feeds
# `SOURCE_DATE_EPOCH` through so the build is reproducible.
#
# Fail-closed: any digest / commit-sha drift aborts before write.

set -euo pipefail
umask 022

if [[ $# -lt 2 ]]; then
    echo "usage: $0 EDK2_TAG EDK2_COMMIT [WORKDIR]" >&2
    exit 64
fi

EDK2_TAG="$1"
EDK2_COMMIT="$2"
WORKDIR="${3:-/build/work}"
OUT_DIR=/out
EDK2_URL=https://github.com/tianocore/edk2.git

mkdir -p "$WORKDIR" "$OUT_DIR"

# Clean any partial state from a prior interrupted run — the work dir
# is a bind-mount, so we wipe its CONTENTS not the mountpoint itself.
find "$WORKDIR" -mindepth 1 -maxdepth 1 -exec rm -rf {} +

# Clone shallow at the pinned commit, then verify the commit sha is
# what we asked for (`git clone --depth 1` on a tag still lets the
# server return the tag's current ref — verifying the sha closes that
# gap).
echo "build-ovmf: cloning edk2 at $EDK2_TAG ($EDK2_COMMIT)" >&2
git -C "$WORKDIR" init -q edk2
cd "$WORKDIR/edk2"
git remote add origin "$EDK2_URL"
# Fetch by TAG (server-side allowed everywhere), then verify HEAD's
# sha matches the operator's pinned commit — closes the "operator
# re-points the tag on the remote" gap that fetching the tag alone
# would leave open.
git fetch --depth 1 origin "refs/tags/${EDK2_TAG}:refs/tags/${EDK2_TAG}"
git checkout --detach "refs/tags/${EDK2_TAG}"

GOT=$(git rev-parse HEAD)
if [[ "$GOT" != "$EDK2_COMMIT" ]]; then
    echo "build-ovmf: edk2 commit mismatch" >&2
    echo "  pinned tag:    $EDK2_TAG" >&2
    echo "  expected sha:  $EDK2_COMMIT" >&2
    echo "  got HEAD sha:  $GOT" >&2
    exit 65
fi

# Init ONLY the submodules `OvmfPkg/AmdSev/AmdSevX64.dsc` actually
# needs to compile. `--recursive` would follow openssl's submodules
# (cloudflare-quiche → boringssl → …) which are test/fuzz suites
# orthogonal to the OVMF build and clone for ~hours on emulated arm64.
# Each path is given to `git submodule update --init` directly so the
# top-level openssl source clones but its inner submodules don't.
echo "build-ovmf: initialising edk2's top-level submodules" >&2
# Init ALL top-level submodules (single level, not recursive). edk2's
# .dsc components need most of them — but `--recursive` would follow
# openssl's own submodules (cloudflare-quiche → boringssl → krb5 → …)
# which are openssl's test / fuzz suites, orthogonal to the OVMF
# build and clone for ~hours on emulated arm64. The top-level
# submodules alone provide the source trees the edk2 build references.
git submodule update --init --depth 1

# edk2's BaseTools build + the `build` driver expect these env vars.
# `EDK_TOOLS_PATH` is set by `edksetup.sh` but exporting it before the
# source keeps `make -C BaseTools` happy on first run.
export WORKSPACE="$WORKDIR/edk2"
export EDK_TOOLS_PATH="$WORKSPACE/BaseTools"
export PACKAGES_PATH="$WORKSPACE"
export PYTHON_COMMAND=/usr/bin/python3

echo "build-ovmf: building BaseTools" >&2
make -C BaseTools -j"$(nproc)" >/dev/null

# edk2's `BuildEnv` (sourced by `edksetup.sh`) reads several env vars
# without first defaulting them — incompatible with `set -u`. Bracket
# the source so the unbound-variable check is only relaxed around
# edk2's own scripts.
set +u
# shellcheck disable=SC1091
source ./edksetup.sh BaseTools
set -u

# AmdSevX64 = the OVMF target that emits the SEV-SNP guest metadata
# table (incl. `SNP_KERNEL_HASHES`). The `sev` crate's measurement
# parser refuses to bind the kernel into the launch digest without
# that section.
#
# The .dsc ships a `PREBUILD` directive that runs `OvmfPkg/AmdSev/Grub/
# grub.sh` to bundle an embedded `grub.efi` into the firmware volume
# — a feature for the legacy "OVMF launches grub which launches the
# OS" boot chain. Hippius boots a UKI directly (PE binary loaded by
# OVMF), so the embedded grub is dead weight; the SNP_KERNEL_HASHES
# section we actually depend on is generated by the OVMF reset vector
# / PlatformPei code, independent of the grub prebuild. The PREBUILD
# is also brittle: the script hard-codes legacy grub modules
# (`linuxefi`, `linux_gnu`) that modern Debian grub2 2.12 has merged
# / dropped. Strip the directive before the build to skip the prebuild
# entirely.
echo "build-ovmf: dropping the legacy grub-prebuild + Grub.inf component" >&2
# The .dsc's `PREBUILD` runs `grub.sh` (legacy grub-modules path).
# The `[Components]` `Grub.inf` then embeds the resulting `grub.efi`
# into the firmware volume — both for an embedded-grub boot chain
# Hippius does NOT use (we boot the UKI directly). Strip both so the
# build completes without depending on grub modules whose names have
# changed between grub2 minor versions. The SNP_KERNEL_HASHES section
# we depend on is generated by the OVMF reset-vector / PlatformPei
# code, independent of the embedded grub.
sed -i '/^[[:space:]]*PREBUILD[[:space:]]*=/d' OvmfPkg/AmdSev/AmdSevX64.dsc
sed -i '/OvmfPkg\/AmdSev\/Grub\/Grub\.inf/d'  OvmfPkg/AmdSev/AmdSevX64.dsc
# `.fdf` lists Grub.efi as a FILE entry inside `MEMFD` — also drop.
if [[ -f OvmfPkg/AmdSev/AmdSevX64.fdf ]]; then
    # Remove the `FILE FREEFORM <UUID> { … Grub.efi … }` block. edk2
    # `.fdf` FILE blocks contain only `SECTION` lines (no nested
    # braces), so a single boolean "we're inside the block, drop
    # everything until the next `}`" is sufficient and bounded.
    python3 - <<'PY'
from pathlib import Path
p = Path("OvmfPkg/AmdSev/AmdSevX64.fdf")
text = p.read_text()
out = []
in_block = False
for line in text.splitlines(keepends=True):
    if in_block:
        # Drop every line of the FILE block — including its own
        # opener and closer — until (and INCLUDING) the matching `}`,
        # then resume normal emission. `}` ends ONE brace level
        # (.fdf FILE blocks are not nested), so this never over-drops.
        if "}" in line:
            in_block = False
        continue
    if "Grub.efi" in line or "Grub/Grub.inf" in line:
        # The current FILE block referenced grub — backtrack the
        # `FILE … {` opener we just emitted and enter skip mode for
        # the rest of the block (we'll re-see the opener line again
        # in the loop because we set in_block from the body, not the
        # opener — so backtrack BEFORE setting in_block).
        if out and "FILE " in out[-1] and "{" in out[-1]:
            out.pop()
        in_block = True
        continue
    out.append(line)
if in_block:
    raise SystemExit("build-ovmf .fdf patch: opened a FILE block but never saw `}` — refusing to ship a corrupted fdf")
p.write_text("".join(out))
PY
fi

echo "build-ovmf: running edk2 build for OvmfPkg/AmdSev/AmdSevX64.dsc" >&2
build \
    -p OvmfPkg/AmdSev/AmdSevX64.dsc \
    -a X64 \
    -t GCC \
    -b RELEASE \
    -DTPM2_ENABLE=FALSE \
    -DBUILD_SHELL=FALSE \
    -DSECURE_BOOT_ENABLE=FALSE \
    >/dev/null

# Output layout: edk2 writes to `Build/<DscBaseName>/<BUILD>_<TOOL>/FV/`.
# `OvmfPkg/AmdSev/AmdSevX64.dsc` uses `PLATFORM_NAME = AmdSev` today; a
# `find` keeps us robust against a future upstream rename.
FD=$(find Build -name OVMF.fd 2>/dev/null | head -n 1)
if [[ -z "$FD" || ! -f "$FD" ]]; then
    echo "build-ovmf: no OVMF.fd produced under Build/" >&2
    find Build -name '*.fd' 2>/dev/null >&2
    exit 66
fi

install -m 0644 "$FD" "$OUT_DIR/OVMF.fd"
SHA=$(sha256sum "$OUT_DIR/OVMF.fd" | awk '{print $1}')
SIZE=$(stat -c %s "$OUT_DIR/OVMF.fd")
echo "build-ovmf: OK — $OUT_DIR/OVMF.fd ($SIZE bytes, sha256=$SHA)" >&2
echo "$SHA" > "$OUT_DIR/OVMF.fd.sha256"
