# Generated by Django 5.2.15 on 2026-07-19 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_throttle_cache_table'),
        ('tenant_bake', '0003_luks_header_sha256'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tenantbake',
            name='tenant_bake_succeeded_requires_qcow2_sha',
        ),
        migrations.RenameIndex(
            model_name='tenantbake',
            new_name='tenant_bake_vm_id_e8f500_idx',
            old_name='tenant_bake_vm_id_18a6c4_idx',
        ),
        migrations.RenameIndex(
            model_name='tenantbake',
            new_name='tenant_bake_state_045061_idx',
            old_name='tenant_bake_state_71e0b5_idx',
        ),
        migrations.AddField(
            model_name='tenantbake',
            name='disk_mode',
            field=models.CharField(choices=[('legacy_luks', 'Legacy LUKS'), ('golden_verity_overlay', 'Golden dm-verity overlay')], default='legacy_luks', max_length=32),
        ),
        migrations.AddField(
            model_name='tenantbake',
            name='rootfs_img_sha256',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='tenantbake',
            name='rootfs_verity_sha256',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='tenantbake',
            name='verity_root_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddConstraint(
            model_name='tenantbake',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('state', 'succeeded'), _negated=True), models.Q(('disk_mode', 'legacy_luks'), _negated=True), models.Q(('qcow2_sha256', ''), _negated=True), _connector='OR'), name='tenant_bake_succeeded_requires_qcow2_sha'),
        ),
        migrations.AddConstraint(
            model_name='tenantbake',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('state', 'succeeded'), _negated=True), models.Q(('disk_mode', 'golden_verity_overlay'), _negated=True), models.Q(models.Q(('rootfs_img_sha256', ''), _negated=True), models.Q(('rootfs_verity_sha256', ''), _negated=True), models.Q(('verity_root_hash', ''), _negated=True)), _connector='OR'), name='tenant_bake_succeeded_golden_requires_verity'),
        ),
    ]
